# Generated by Django 5.2.9 on 2025-12-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationusers',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
