# Generated by Django 4.2.25 on 2025-12-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_ticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
