# Generated by Django 5.2.9 on 2025-12-16 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_ticket_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettier',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='App.event'),
        ),
    ]
