# Generated by Django 5.2.9 on 2025-12-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_tickettier_event'),
        ('App', '0004_remove_event_organizer_event_organization'),
    ]

    operations = [
    ]
