# Generated by Django 4.2.25 on 2025-12-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_merge_20251216_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('Non-active', 'Non-active')], default='pending', max_length=10),
        ),
    ]
