# Generated by Django 5.2.9 on 2025-12-17 15:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_merge_20251216_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('Non-active', 'Non-active')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
