<<<<<<< HEAD
# Generated by Django 5.2.9 on 2025-12-16 21:39
=======
# Generated by Django 4.2.25 on 2025-12-16 21:53
>>>>>>> f016da1056003e99f9c72d0f9ad0b047b4185e1a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('App', '0005_merge_20251216_1501'),
=======
        ('App', '0005_merge_20251216_2103'),
>>>>>>> f016da1056003e99f9c72d0f9ad0b047b4185e1a
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('Non-active', 'Non-active')], default='pending', max_length=10),
        ),
    ]
