# Generated by Django 5.2.9 on 2025-12-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tickettier',
            name='price',
            field=models.IntegerField(),
        ),
    ]
