# Generated by Django 5.2.9 on 2025-12-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_cart_ticketssaved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketssaved',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
