# Generated by Django 5.2.9 on 2025-12-17 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_ticketssaved_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketssaved',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='App.cart'),
        ),
    ]
