# Generated by Django 5.2.9 on 2025-12-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_ticketssaved_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketssaved',
            old_name='tickets',
            new_name='ticket',
        ),
    ]
