# Generated by Django 5.2.9 on 2025-12-18 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_rename_tickets_ticketssaved_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='event',
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='App.order'),
        ),
        migrations.AlterField(
            model_name='tickettier',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
