# Generated by Django 5.2.9 on 2026-01-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_remove_order_event_alter_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, default='event_images/default eventimage.png', null=True, upload_to='event_images/'),
        ),
    ]
