# Generated by Django 5.2.9 on 2026-01-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_event_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, default='event_images/default_eventimage.png', null=True, upload_to='event_images/'),
        ),
    ]
